import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { LoadingProvider } from "@/common/contexts/LoadingContext";
import { Toaster } from "sonner";
import { ReduxProvider } from "@/redux/provider";
import Header from "@/components/Homepage/Header";
import Footer from "@/components/Homepage/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <ReduxProvider>
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
          <Header />

          <Toaster position="top-right" expand={false} richColors />
          <LoadingProvider>{children}</LoadingProvider>
          <Footer />
        </body>
      </ReduxProvider>
    </html>
  );
}
