version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - '${PORT}:${PORT}'
    depends_on:
      - postgres
      - redis
    env_file:
      - .env.local
    volumes:
      - .:/app
      - /app/node_modules
    command: pnpm dev

  postgres:
    image: postgres:15-alpine
    ports:
      - '${DB_PORT}:${DB_PORT}'
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - postgres_local_data:/var/lib/postgresql/data
    env_file:
      - .env.local

  redis:
    image: redis:alpine
    ports:
      - '${REDIS_PORT}:${REDIS_PORT}'
    command: redis-server --requirepass ${REDIS_PASSWORD}
    volumes:
      - redis_local_data:/data
    env_file:
      - .env.local

  pgadmin:
    image: dpage/pgadmin4
    ports:
      - '5050:80'
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - postgres

volumes:
  postgres_local_data:
  redis_local_data:
  pgadmin_data:
